--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/27/2022 3:32:42 PM
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `misa.web09.qtkd.ndtrung`;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Drop table `jobposition`
--
DROP TABLE IF EXISTS jobposition;

--
-- Set default database
--
USE `misa.web09.qtkd.ndtrung`;

--
-- Create table `jobposition`
--
CREATE TABLE jobposition (
  jobPostionID char(36) NOT NULL DEFAULT '' COMMENT 'ID Chức danh',
  jobPostionCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã chức danh',
  jobPostionName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên chức danh',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedBy varchar(255) DEFAULT NULL COMMENT 'Người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa gần nhất',
  ModifiedBy varchar(255) DEFAULT NULL COMMENT 'Ngày chỉnh sửa gần nhất',
  PRIMARY KEY (jobPostionID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Bảng thông tin chức danh';

--
-- Create index `IX_jobPosition_jobPositionCode` on table `jobposition`
--
ALTER TABLE jobposition
ADD UNIQUE INDEX IX_jobPosition_jobPositionCode (jobPostionCode);

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentID char(36) NOT NULL DEFAULT '' COMMENT 'ID đơn vị',
  DepartmentCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã đơn vị',
  DepartmentName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên đơn vị',
  CreatedDate date DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa gần nhất',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa gần nhất',
  PRIMARY KEY (DepartmentID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Bảng thông tin đơn vị';

--
-- Create index `IX_Department_DepartmentCode` on table `department`
--
ALTER TABLE department
ADD UNIQUE INDEX IX_Department_DepartmentCode (DepartmentCode);

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeID char(36) NOT NULL DEFAULT '' COMMENT 'ID nhân viên',
  EmployeeCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã nhân viên',
  EmployeeName varchar(100) NOT NULL DEFAULT '' COMMENT 'Tên nhân viên',
  DateOfBirth date DEFAULT NULL COMMENT 'Ngày sinh',
  Gender tinyint DEFAULT NULL COMMENT 'Giới tính (0: Khác, 1: Nam; 2: Nữ',
  IdentityNumber varchar(255) DEFAULT NULL COMMENT 'Số CMND',
  IdentityIssuedDate date DEFAULT NULL COMMENT 'Ngày cấp',
  IdentityIssuedPlace varchar(255) DEFAULT NULL COMMENT 'Nơi cấp',
  jobPositionID char(36) DEFAULT NULL COMMENT 'ID chức danh',
  jobPostionName varchar(255) DEFAULT NULL COMMENT 'Tên chức danh',
  DepartmentID char(36) NOT NULL DEFAULT '' COMMENT 'ID Đơn vị',
  DepartmentName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên đơn vị',
  PhoneNumber varchar(50) DEFAULT NULL COMMENT 'Điện thoại di động',
  TelephoneNumber varchar(50) DEFAULT NULL COMMENT 'Điện thoại cố định',
  Email varchar(100) DEFAULT NULL COMMENT 'Email',
  BankAccountNumber varchar(25) DEFAULT NULL COMMENT 'Tài Khoản Ngân Hàng',
  BankName varchar(255) DEFAULT NULL COMMENT 'Tên ngân hàng',
  BankBranchName varchar(255) DEFAULT NULL COMMENT 'Chi nhánh',
  Address varchar(255) DEFAULT NULL COMMENT 'Địa chỉ',
  CreatedDate date DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo',
  ModifiedDate date DEFAULT NULL COMMENT 'Ngày chỉnh sửa gần nhất',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa gần nhất',
  PRIMARY KEY (EmployeeID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Bảng thông tin nhân viên';

--
-- Create index `IX_Employee_EmployeeCode` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX IX_Employee_EmployeeCode (EmployeeCode);

--
-- Create index `IX_Employee_EmployeeName` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX IX_Employee_EmployeeName (EmployeeName);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_employee_department_DepartmentID FOREIGN KEY (DepartmentID)
REFERENCES department (DepartmentID);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_employee_jobPosition_jobPositionID FOREIGN KEY (jobPositionID)
REFERENCES jobposition (jobPostionID);

-- 
-- Dumping data for table jobposition
--
-- Table `misa.web09.qtkd.ndtrung`.jobposition does not contain any data (it is empty)

-- 
-- Dumping data for table department
--
-- Table `misa.web09.qtkd.ndtrung`.department does not contain any data (it is empty)

-- 
-- Dumping data for table employee
--
-- Table `misa.web09.qtkd.ndtrung`.employee does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;